#WMCA
WMCA_root: ""
WMCA_train_protocol : ""
WMCA_test_protocol : ""
#PADISI
PADISI_root: ""
PADISI_train_protocol : ""
PADISI_test_protocol : ""
#SURF
SURF_root: ""
SURF_train_protocol : ""
SURF_test_protocol : ""
#CeFA
CeFA_root: ""
CeFA_train_protocol : ""
CeFA_test_protocol : ""